export {SettingsIcon} from './SettingsIcon'
export {HandsIcon} from './HandsIcon'
export {PlusIcon} from './PlusIcon'
export {MessageIcon} from './MessageIcon'
export {SmallPlusIcon} from './SmallPlusIcon'
